name: Build and run unit tests on selected project

# run upon a push to the integration branch 
on:
  push:
    branches: integration

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'           # set this to the dot net version to use
  PROJECT_PATH: './Fuji_Example'
  PROJECT_NAME: 'Fuji_Tests'
  JS_PROJECT_NAME: 'Fuji_JSTests'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains multiple jobs.  All are executed on the same virtual machine
  build_job:
    name: Build all .NET projects
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # They are executed in order
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 

      # Runs a single command using the runners shell (just as an example that we can do anything the shell can do)
      - name: Run a one-line script
        run: echo Hello, world!
        
      # Build the selected project
      - name: Build project
        working-directory: ${{ env.PROJECT_PATH }}
        run: |
          dotnet restore
          dotnet build 
  # Run unit tests in a separate job, that is dependent on the build job
  unit_tests_job:
    name: Run all C# unit tests
    needs: build_job
    steps:
      # Test the selected project
      - name: Run unit tests on the main project
        working-directory: ${{ env.PROJECT_PATH }}
        run: dotnet test --no-restore --no-build ${{ env.PROJECT_NAME }}